### ISSUE TITLE
Table header 

### ISSUE THREAD

**Issue by TwinMist** [erikfva/phpmaker-plugins#3]
Hi
the table header is still notshowing with latest pull.

thanks

**Comment by erikfva** [comment]
Table header fixed functionality is done add https://github.com/erikfva/tableheadfixer.git repository
1.- After clone/copy **plugins** repository, open command console and go to folder: plugins/plg_coolui and clone or copy repository https://github.com/erikfva/tableheadfixer.git.
**_git clone https://github.com/erikfva/tableheadfixer.git_**

**Comment by TwinMist** [comment]
Should this not be built into it?
